/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.ControlDistribuidores;
import Modelo.Distribuidor;
import Modelo.Planta;
import Modelo.TipoReproduccion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Valentina
 */
public class DistribuidoresAddUI extends javax.swing.JInternalFrame {
    private ControlDistribuidores controlDistribuidores;
    /**
     * Creates new form DistribuidoresAddUI
     */
    public DistribuidoresAddUI() {
        initComponents();
          controlDistribuidores = new ControlDistribuidores();

        addbtn.addActionListener(new agregarDistribuidorListener());
        TextPrompt nombre = new TextPrompt("Nombre", nomjT);
        TextPrompt nit = new TextPrompt("Nit", nitjT);
        TextPrompt tel = new TextPrompt("Teléfono", teljT);
        TextPrompt email = new TextPrompt("email", emailjT);
        TextPrompt ciudad = new TextPrompt("Ciudad", ciudadjT);
        TextPrompt direccion = new TextPrompt("Dirección", dirjT);
       

//        agregarbtn.addActionListener(new PlantasUI.agregarPlantaListener());
        cancelbtn.addActionListener(new borrarListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nitjT = new javax.swing.JTextField();
        nomjT = new javax.swing.JTextField();
        teljT = new javax.swing.JTextField();
        ciudadjT = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        emailjT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dirjT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Añadir Nuevo Distribuidor");

        nitjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nitjT.setBorder(null);
        nitjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nitjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        nitjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitjTActionPerformed(evt);
            }
        });

        nomjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nomjT.setBorder(null);
        nomjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nomjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        nomjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomjTActionPerformed(evt);
            }
        });

        teljT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        teljT.setBorder(null);
        teljT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        teljT.setSelectionColor(new java.awt.Color(133, 198, 90));
        teljT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teljTActionPerformed(evt);
            }
        });

        ciudadjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ciudadjT.setBorder(null);
        ciudadjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ciudadjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        ciudadjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadjTActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonAdd.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.setBorderPainted(false);
        addbtn.setContentAreaFilled(false);

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonCancel.png"))); // NOI18N
        cancelbtn.setBorder(null);
        cancelbtn.setBorderPainted(false);
        cancelbtn.setContentAreaFilled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        emailjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        emailjT.setBorder(null);
        emailjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        emailjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        dirjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dirjT.setBorder(null);
        dirjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dirjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        dirjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirjTActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(cancelbtn)
                .addGap(123, 123, 123)
                .addComponent(addbtn)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dirjT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nitjT)
                        .addComponent(nomjT)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailjT)
                        .addComponent(ciudadjT)
                        .addComponent(teljT)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nitjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(teljT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(emailjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addComponent(dirjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(ciudadjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addbtn)
                    .addComponent(cancelbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nitjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitjTActionPerformed

    private void nomjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomjTActionPerformed

    private void teljTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teljTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teljTActionPerformed

    private void ciudadjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadjTActionPerformed

    private void emailjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTActionPerformed

    private void dirjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirjTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField ciudadjT;
    private javax.swing.JTextField dirjT;
    private javax.swing.JTextField emailjT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nitjT;
    private javax.swing.JTextField nomjT;
    private javax.swing.JTextField teljT;
    // End of variables declaration//GEN-END:variables
  public class agregarDistribuidorListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long nit = Long.parseLong(nitjT.getText());
                String nom = nomjT.getText();
                long tel = Long.parseLong(teljT.getText());
                String email = emailjT.getText();
                String direccion = dirjT.getText();
                String ciudad = ciudadjT.getText();
                Distribuidor d = new Distribuidor(nit, nom, tel, email, direccion, ciudad);
                controlDistribuidores.agregarDistribuidor(d);
                JOptionPane.showMessageDialog(rootPane, "Distribuidor agregado con éxito");
                cancelbtn.doClick();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }

    }

    public class borrarListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            nitjT.setText("");
            nomjT.setText("");
            teljT.setText("");
            emailjT.setText("");
            ciudadjT.setText("");
            dirjT.setText("");
        }

    }


}
