/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.ControlDetallePedido;
import Control.ControlIngresos;
import Control.ControlPedidos;
import Modelo.Detalle_Pedido;
import Modelo.Distribuidor;
import Modelo.Ingreso;
import Modelo.Pedido;
import Modelo.Planta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Valentina
 */
public class IngresosAñadirUI extends javax.swing.JInternalFrame {

    Pedido pedido;
    Distribuidor distribuidor;
    Ingreso ingreso;
    Planta planta;
    ControlPedidos cp = new ControlPedidos();
    ControlIngresos ci = new ControlIngresos();
    ControlDetallePedido dp = new ControlDetallePedido();
    int Valortotalpedido = 0;
    int cantidadtotalpedido = 0;

    /**
     * Creates new form SiembrasAñadirUI
     */
    public IngresosAñadirUI() {
        initComponents();
        this.close.addMouseListener(new clickCerrarListener());
        this.close1.addMouseListener(new clickCerrarListener());
        setLocation(0, -32);

        this.agregarbtn.addActionListener(new agregarIngresoListener());
        this.cancelarbtn.addActionListener(new CancelarListener());
        BuscarPedidoListener bpl = new BuscarPedidoListener();
        this.buscarbtn.addActionListener(bpl);
        this.conPagoJT.addActionListener(new confirmarPago());

        entregajT.setEditable(false);
        vlrVendidojT.setEditable(false);
        pagojT.setEditable(false);
        nitjT.setEditable(false);
        nomCliejT.setEditable(false);
        cantProdjT.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entregajT = new javax.swing.JTextField();
        agregarbtn = new javax.swing.JButton();
        cantProdjT = new javax.swing.JTextField();
        vlrVendidojT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pagojT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancelarbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pedidojT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingresoTable = new javax.swing.JTable();
        nomCliejT = new javax.swing.JTextField();
        nitjT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscarbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        conPagoJT = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(108, 169, 62));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/plus (2).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Agregar nuevo Ingreso");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N

        close1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("Cerrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(close1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Valor total vendido:");

        agregarbtn.setText("Agregar Ingreso");

        cantProdjT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vlrVendidojT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Número de pedido:");

        pagojT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nit:");

        cancelarbtn.setText("Cancelar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombre cliente:");

        pedidojT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ingresoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Producto", "Cantidad vendida", "Valor unitario", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(ingresoTable);

        nomCliejT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        nitjT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Estado de pago:");

        buscarbtn.setText(". . .");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cantidad total de productos vendidos:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Estado de entrega:");

        conPagoJT.setText("Confirmar Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(cancelarbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarbtn)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(conPagoJT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(11, 11, 11)
                                    .addComponent(entregajT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel6)
                                    .addGap(10, 10, 10)
                                    .addComponent(cantProdjT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel5)
                                    .addGap(11, 11, 11)
                                    .addComponent(pagojT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(190, 190, 190)
                                    .addComponent(jLabel7)
                                    .addGap(10, 10, 10)
                                    .addComponent(vlrVendidojT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel2)
                                    .addGap(28, 28, 28)
                                    .addComponent(pedidojT, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(buscarbtn))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel3)
                                    .addGap(22, 22, 22)
                                    .addComponent(nitjT, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel4)
                                    .addGap(26, 26, 26)
                                    .addComponent(nomCliejT, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(conPagoJT)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarbtn)
                    .addComponent(agregarbtn))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(buscarbtn)
                        .addComponent(pedidojT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3))
                        .addComponent(nitjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(nomCliejT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(entregajT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel6))
                        .addComponent(cantProdjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(pagojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(vlrVendidojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarbtn;
    private javax.swing.JButton buscarbtn;
    private javax.swing.JButton cancelarbtn;
    private javax.swing.JTextField cantProdjT;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JButton conPagoJT;
    private javax.swing.JTextField entregajT;
    private javax.swing.JTable ingresoTable;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nitjT;
    private javax.swing.JTextField nomCliejT;
    private javax.swing.JTextField pagojT;
    private javax.swing.JTextField pedidojT;
    private javax.swing.JTextField vlrVendidojT;
    // End of variables declaration//GEN-END:variables
    public class clickCerrarListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {

            setVisible(false);

        }

        @Override
        public void mousePressed(MouseEvent e) {

        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }

        @Override
        public void mouseEntered(MouseEvent e) {

        }

        @Override
        public void mouseExited(MouseEvent e) {

        }

    }

    public class BuscarPedidoListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            if (pedidojT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "El campo codigo está vacio");
            } else {
                long codigo = Long.parseLong(pedidojT.getText());
                try {
                    pedido = cp.buscarPedido(codigo);

                    nitjT.setText(Long.toString(pedido.getDistribuidor().getNit()));
                    nomCliejT.setText(pedido.getDistribuidor().getNombre());
                    entregajT.setText(pedido.getEstadoEntrega().toString());
                    pagojT.setText(pedido.getEstadoPago());

                    ingresoTable.setModel(new IngresosTableModel());
                    for (int i = 0; i < pedido.getListaDetallePedido().size(); i++) {

                        cantidadtotalpedido = cantidadtotalpedido + pedido.getListaDetallePedido().get(i).getCantidad();
                        Valortotalpedido = Valortotalpedido + (pedido.getListaDetallePedido().get(i).getCantidad() * pedido.getListaDetallePedido().get(i).getPlanta().getValor_unitario());

                    }
                    cantProdjT.setText(Integer.toString(cantidadtotalpedido));
                    vlrVendidojT.setText(Integer.toString(Valortotalpedido));

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "El codigo es incorrecto");
                    Logger.getLogger(IngresosUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public class confirmarPago implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            if (pagojT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "El campo está vacio");
            } else {
                try {

                    pedido.setEstadoPago("Pago");
                    pagojT.setText(pedido.getEstadoPago());
                    JOptionPane.showMessageDialog(rootPane, "El pago se ha confirmado");

                } catch (Exception ex) {
                    Logger.getLogger(IngresosUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }

    public class agregarIngresoListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            if (pedidojT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "No hay datos que ingresar");
            } else {

                try {
                    int total = Integer.parseInt(vlrVendidojT.getText());

                    ingreso = new Ingreso(total, pedido);

                    ingresoTable.updateUI();

                    pedidojT.setText("");
                    nitjT.setText("");
                    nomCliejT.setText("");

                    cantProdjT.setText("");
                    vlrVendidojT.setText("");
                    entregajT.setText("");
                    pagojT.setText("");

                    try {
                        ingresoTable.setModel(new DefaultTableModel());
                        cp.actualizarPedido(pedido);
                        ci.agregarIngresos(ingreso);
                        JOptionPane.showMessageDialog(rootPane, "El ingreso a sido realizado exitosamente");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(rootPane, "Error: " + ex.getMessage());
                    }

                } catch (Exception ex) {
                    Logger.getLogger(IngresosUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    public class IngresosTableModel implements TableModel {

        @Override
        public int getRowCount() {
            return pedido.getListaDetallePedido().size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Detalle_Pedido detalle = pedido.getListaDetallePedido().get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return detalle.getPlanta().getNombre();
                case 1:

                    return detalle.getCantidad();
                case 2:
                    return detalle.getPlanta().getValor_unitario();
                case 3:
                    int valorsubtotal = detalle.getCantidad() * detalle.getPlanta().getValor_unitario();
                    return valorsubtotal;
            }
            return " ";
        }

        private String[] nombreColumnas = {"Nombre Producto", "Cantidad Vendida", "Vlr. unidad", "Subtotal"};

        @Override
        public String getColumnName(int columnIndex) {
            return nombreColumnas[columnIndex];
        }

        private Class[] tipoColumnas = {Integer.class, Integer.class, Integer.class, Integer.class};

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            // return String.class;
            return tipoColumnas[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }

        @Override
        public void addTableModelListener(TableModelListener l) {

        }

        @Override
        public void removeTableModelListener(TableModelListener l) {

        }

    }

    public class CancelarListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            pedidojT.setText("");
            nitjT.setText("");
            nomCliejT.setText("");
            cantProdjT.setText("");
            vlrVendidojT.setText("");
            entregajT.setText("");
            pagojT.setText("");

            ingresoTable.updateUI();
            JOptionPane.showMessageDialog(rootPane, "El ingreso se cancelo");
        }
    }

}
