package UI;

import Control.ControlPlantas;
import Modelo.Planta;
import Modelo.TipoReproduccion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

public class PlantaEditarUI extends javax.swing.JInternalFrame {

    private ControlPlantas controlPlantas;
    private Planta p;

    public PlantaEditarUI() {
        initComponents();
        this.controlPlantas = new ControlPlantas();
        this.plantasjC.setModel(new PlantasListener());
        this.acbtn.addActionListener(new EditPlantaListener());
        this.canbtn.addActionListener(new borrarListener());
        this.plantasjC.addActionListener(new buscarPlantaListener());
        setLocation(0, -32);
        this.close.addMouseListener(new clickCerrarListener());
        this.close1.addMouseListener(new clickCerrarListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        plantasjC = new javax.swing.JComboBox();
        precioNjT = new javax.swing.JTextField();
        tCrecjT = new javax.swing.JTextField();
        tGerjT = new javax.swing.JTextField();
        nomPjT = new javax.swing.JTextField();
        tRepjC = new javax.swing.JComboBox(TipoReproduccion.values());
        ;
        tReprod = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        acbtn = new javax.swing.JButton();
        canbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 571));
        setRequestFocusEnabled(false);

        precioNjT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        precioNjT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        precioNjT.setSelectionColor(new java.awt.Color(133, 198, 90));

        tCrecjT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tCrecjT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tCrecjT.setSelectionColor(new java.awt.Color(133, 198, 90));

        tGerjT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tGerjT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tGerjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        tGerjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGerjTActionPerformed(evt);
            }
        });

        nomPjT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nomPjT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nomPjT.setSelectionColor(new java.awt.Color(133, 198, 90));

        tRepjC.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        tReprod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        cod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(153, 153, 153));

        acbtn.setBackground(new java.awt.Color(255, 255, 255));
        acbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/actualizar.png"))); // NOI18N
        acbtn.setBorder(null);
        acbtn.setBorderPainted(false);
        acbtn.setContentAreaFilled(false);

        canbtn.setBackground(new java.awt.Color(255, 255, 255));
        canbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonCancel.png"))); // NOI18N
        canbtn.setBorder(null);
        canbtn.setBorderPainted(false);
        canbtn.setContentAreaFilled(false);

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Seleccione la planta:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Código:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Seleccione el Tipo de Reproducción:");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Tiempo de Germinación:");

        jPanel2.setBackground(new java.awt.Color(108, 169, 62));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit (1).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Editar Planta");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N

        close1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("Cerrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(197, 197, 197)
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(close1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tipo de Reproducción:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Tiempo de Crecimiento:");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Precio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(plantasjC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addComponent(cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomPjT, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(tReprod, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(precioNjT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tCrecjT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tGerjT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(tRepjC, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(canbtn)
                        .addGap(163, 163, 163)
                        .addComponent(acbtn)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(plantasjC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomPjT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tReprod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(tRepjC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tGerjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tCrecjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(1, 1, 1)
                .addComponent(precioNjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acbtn)
                    .addComponent(canbtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tGerjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGerjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGerjTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acbtn;
    private javax.swing.JButton canbtn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nomPjT;
    private javax.swing.JComboBox plantasjC;
    private javax.swing.JTextField precioNjT;
    private javax.swing.JTextField tCrecjT;
    private javax.swing.JTextField tGerjT;
    private javax.swing.JComboBox<String> tRepjC;
    private javax.swing.JLabel tReprod;
    // End of variables declaration//GEN-END:variables

    public class PlantasListener implements ComboBoxModel {

        List<Planta> plantas = controlPlantas.getListaPlantas();
        private Object selected = null;

        @Override

        public void setSelectedItem(Object anItem) {
            this.selected = anItem;
        }

        @Override
        public Object getSelectedItem() {
            return this.selected;
        }

        @Override
        public int getSize() {
            return plantas.size();
        }

        @Override
        public Object getElementAt(int index) {
            return plantas.get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {

        }

        @Override
        public void removeListDataListener(ListDataListener l) {

        }

    }

    public class buscarPlantaListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            p = (Planta) plantasjC.getSelectedItem();
            String codg = p.getCodigo();
            String nom = p.getNombre();
            TipoReproduccion tp = p.getTipoReproduccion();
            int tGer = p.getTiempoGerminacion();
            int tCrec = p.getTiempoCrecimiento();
            int precio = p.getValor_unitario();
            tRepjC.setSelectedItem(tp);
            cod.setText(codg);
            nomPjT.setText(nom);
            tReprod.setText(tp.toString());
            tGerjT.setText(Integer.toString(tGer));
            tCrecjT.setText(Integer.toString(tCrec));
            precioNjT.setText(Integer.toString(precio));
            tReprod.setText(p.getTipoReproduccion().toString());

        }

    }

    public class EditPlantaListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (cod.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un Código");
            }
            if (nomPjT.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un nombre");
                String n = p.getNombre();
                p.setNombre(n);

            }
            if (tGerjT.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un tiempo de Germinación");
            }
            if (tCrecjT.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un tiempo de Crecimiento");
            }
            if (precioNjT.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un precio");
            } else {
                try {
                    String nom = nomPjT.getText();
                    TipoReproduccion tr = (TipoReproduccion) tRepjC.getSelectedItem();
                    int tGer = Integer.parseInt(tGerjT.getText());
                    int tCrec = Integer.parseInt(tCrecjT.getText());
                    int precio = Integer.parseInt(precioNjT.getText());
                    p = (Planta) plantasjC.getSelectedItem();
                    p.setValor_unitario(precio);
                    p.setNombre(nom);
                    p.setTipoReproduccion(tr);
                    p.setTiempoGerminacion(tGer);
                    p.setTiempoCrecimiento(tCrec);
                    controlPlantas.actualizarPlanta(p);
                    JOptionPane.showMessageDialog(rootPane, "Planta editada con éxito");
                    canbtn.doClick();
                } catch (Exception ex) {
                    Logger.getLogger(PlantaEditarUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }

    public class borrarListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            nomPjT.setText("");
            cod.setText("");
            tCrecjT.setText("");
            tGerjT.setText("");

            precioNjT.setText("");

        }

    }

    public class clickCerrarListener implements MouseListener {

        private PlantasAñadirUI plantasAddUI;

        @Override
        public void mouseClicked(MouseEvent e) {

            setVisible(false);

        }

        @Override
        public void mousePressed(MouseEvent e) {

        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }

        @Override
        public void mouseEntered(MouseEvent e) {

        }

        @Override
        public void mouseExited(MouseEvent e) {

        }

    }
}
