/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.ControlPlantas;
import Modelo.Planta;
import Modelo.TipoReproduccion;
import Resources.fondoDesktop;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author Valentina
 */
public class PlantasAñadirUI extends javax.swing.JInternalFrame {

    private ControlPlantas controlPlantas;

    public PlantasAñadirUI() {
        initComponents();
//        this.cancelbtn.setBorder(new );

        controlPlantas = new ControlPlantas();

        addbtn.addActionListener(new agregarPlantaListener());
        TextPrompt nombre = new TextPrompt("Ingrese un nombre", nombrejT);
        TextPrompt codigo = new TextPrompt("Ingrese un código", codigojT);
        TextPrompt tGerminacion = new TextPrompt("Ingrese el Tiempo de Germinación", tGermjT);
        TextPrompt tCrecimiento = new TextPrompt("Ingrese el Tiempo de Crecimiento", tCrecjT);
        TextPrompt precio = new TextPrompt("Ingrese el precio", preciojT);
        controlPlantas = new ControlPlantas();
        this.close.addMouseListener(new clickCerrarListener());
        this.close1.addMouseListener(new clickCerrarListener());
        setLocation(0, -32);

//        agregarbtn.addActionListener(new PlantasUI.agregarPlantaListener());
        cancelbtn.addActionListener(new borrarListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrejT = new javax.swing.JTextField();
        tGermjT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tCrecjT = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        preciojT = new javax.swing.JTextField();
        tReprodjC = new javax.swing.JComboBox(TipoReproduccion.values());
        ;
        cancelbtn = new javax.swing.JButton();
        codigojT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        nombrejT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nombrejT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nombrejT.setSelectionColor(new java.awt.Color(133, 198, 90));
        nombrejT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrejTActionPerformed(evt);
            }
        });

        tGermjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tGermjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tGermjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        tGermjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGermjTActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Precio:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Tiempo de crecimiento:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("TIpo de reproducción:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tiempo de germinación:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Código:");

        tCrecjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tCrecjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tCrecjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        tCrecjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCrecjTActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonAdd.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.setBorderPainted(false);
        addbtn.setContentAreaFilled(false);

        preciojT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        preciojT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        preciojT.setSelectionColor(new java.awt.Color(133, 198, 90));
        preciojT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciojTActionPerformed(evt);
            }
        });

        tReprodjC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tReprodjC.setForeground(new java.awt.Color(102, 102, 102));
        tReprodjC.setBorder(null);

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonCancel.png"))); // NOI18N
        cancelbtn.setBorder(null);
        cancelbtn.setBorderPainted(false);
        cancelbtn.setContentAreaFilled(false);

        codigojT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        codigojT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        codigojT.setSelectionColor(new java.awt.Color(133, 198, 90));
        codigojT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigojTActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(108, 169, 62));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/plus (2).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Agregar nueva planta");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N

        close1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("Cerrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(close1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(cancelbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addbtn)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tCrecjT)
                    .addComponent(tReprodjC, 0, 314, Short.MAX_VALUE)
                    .addComponent(codigojT)
                    .addComponent(nombrejT)
                    .addComponent(tGermjT)
                    .addComponent(preciojT))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrejT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tGermjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tCrecjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tReprodjC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preciojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addbtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrejTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrejTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrejTActionPerformed

    private void codigojTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigojTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigojTActionPerformed

    private void tCrecjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCrecjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCrecjTActionPerformed

    private void preciojTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciojTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciojTActionPerformed

    private void tGermjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGermjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGermjTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JTextField codigojT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombrejT;
    private javax.swing.JTextField preciojT;
    private javax.swing.JTextField tCrecjT;
    private javax.swing.JTextField tGermjT;
    private javax.swing.JComboBox<TipoReproduccion> tReprodjC;
    // End of variables declaration//GEN-END:variables

    public class agregarPlantaListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                String cod = codigojT.getText();
                String nom = nombrejT.getText();
                int germinacion = Integer.parseInt(tGermjT.getText());
                int crecimiento = Integer.parseInt(tCrecjT.getText());
                TipoReproduccion tr = (TipoReproduccion) tReprodjC.getSelectedItem();
                int precio = Integer.parseInt(preciojT.getText());
                Planta p = new Planta(cod, nom, germinacion, crecimiento, tr, precio);
                controlPlantas.agregarPlanta(p);
                JOptionPane.showMessageDialog(rootPane, "Planta agregada con éxito");
                cancelbtn.doClick();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }

    }

    public class borrarListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            codigojT.setText("");
            nombrejT.setText("");
            tGermjT.setText("");
            tCrecjT.setText("");
            preciojT.setText("");
        }

    }

    public class clickCerrarListener implements MouseListener {

        private PlantasAñadirUI plantasAddUI;

        @Override
        public void mouseClicked(MouseEvent e) {

            setVisible(false);

        }

        @Override
        public void mousePressed(MouseEvent e) {

        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }

        @Override
        public void mouseEntered(MouseEvent e) {

        }

        @Override
        public void mouseExited(MouseEvent e) {

        }

    }

}
