/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.ControlPlantas;
import Modelo.Planta;
import Modelo.TipoReproduccion;
import Resources.fondoDesktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Valentina
 */
public class PlantasAddUI extends javax.swing.JInternalFrame {

    private ControlPlantas controlPlantas;

    public PlantasAddUI() {
        initComponents();
//        this.cancelbtn.setBorder(new );

        controlPlantas = new ControlPlantas();

        addbtn.addActionListener(new agregarPlantaListener());
        TextPrompt nombre = new TextPrompt("Nombre", nombrejT);
        TextPrompt codigo = new TextPrompt("Código", codigojT);
        TextPrompt tGerminacion = new TextPrompt("Tiempo de Germinación", tGermjT);
        TextPrompt tCrecimiento = new TextPrompt("Tiempo de Crecimiento", tCrecjT);
        TextPrompt precio = new TextPrompt("Precio", preciojT);
        controlPlantas = new ControlPlantas();

//        agregarbtn.addActionListener(new PlantasUI.agregarPlantaListener());
        cancelbtn.addActionListener(new borrarListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigojT = new javax.swing.JTextField();
        nombrejT = new javax.swing.JTextField();
        tGermjT = new javax.swing.JTextField();
        tReprodjC = new javax.swing.JComboBox(TipoReproduccion.values());
        ;
        preciojT = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tCrecjT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Añadir Nueva Planta");

        codigojT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        codigojT.setBorder(null);
        codigojT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        codigojT.setSelectionColor(new java.awt.Color(133, 198, 90));
        codigojT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigojTActionPerformed(evt);
            }
        });

        nombrejT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nombrejT.setBorder(null);
        nombrejT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nombrejT.setSelectionColor(new java.awt.Color(133, 198, 90));
        nombrejT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrejTActionPerformed(evt);
            }
        });

        tGermjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tGermjT.setBorder(null);
        tGermjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tGermjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        tGermjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGermjTActionPerformed(evt);
            }
        });

        tReprodjC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tReprodjC.setForeground(new java.awt.Color(255, 255, 255));
        tReprodjC.setBorder(null);

        preciojT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        preciojT.setBorder(null);
        preciojT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        preciojT.setSelectionColor(new java.awt.Color(133, 198, 90));
        preciojT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciojTActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonAdd.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.setBorderPainted(false);
        addbtn.setContentAreaFilled(false);

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buttonCancel.png"))); // NOI18N
        cancelbtn.setBorder(null);
        cancelbtn.setBorderPainted(false);
        cancelbtn.setContentAreaFilled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        tCrecjT.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tCrecjT.setBorder(null);
        tCrecjT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tCrecjT.setSelectionColor(new java.awt.Color(133, 198, 90));
        tCrecjT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCrecjTActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigojT)
                    .addComponent(nombrejT)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tCrecjT)
                    .addComponent(preciojT)
                    .addComponent(tGermjT)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tReprodjC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(cancelbtn)
                .addGap(43, 43, 43)
                .addComponent(addbtn)
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nombrejT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tGermjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(tCrecjT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(23, 23, 23)
                .addComponent(tReprodjC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(preciojT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addbtn)
                    .addComponent(cancelbtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCrecjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCrecjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCrecjTActionPerformed

    private void preciojTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciojTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciojTActionPerformed

    private void tGermjTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGermjTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGermjTActionPerformed

    private void nombrejTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrejTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrejTActionPerformed

    private void codigojTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigojTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigojTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField codigojT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrejT;
    private javax.swing.JTextField preciojT;
    private javax.swing.JTextField tCrecjT;
    private javax.swing.JTextField tGermjT;
    private javax.swing.JComboBox<TipoReproduccion> tReprodjC;
    // End of variables declaration//GEN-END:variables

    public class agregarPlantaListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                String cod = codigojT.getText();
                String nom = nombrejT.getText();
                int germinacion = Integer.parseInt(tGermjT.getText());
                int crecimiento = Integer.parseInt(tCrecjT.getText());
                TipoReproduccion tr = (TipoReproduccion) tReprodjC.getSelectedItem();
                int precio = Integer.parseInt(preciojT.getText());
                Planta p = new Planta(cod, nom, germinacion, crecimiento, tr, precio);
                controlPlantas.agregarPlanta(p);
                JOptionPane.showMessageDialog(rootPane, "Planta agregada con éxito");
                //cancelbtn.doClick();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }

    }

    public class borrarListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            codigojT.setText("");
            nombrejT.setText("");
            tGermjT.setText("");
            tCrecjT.setText("");
            preciojT.setText("");
        }

    }

}
